export class StoreSettingDto {
    autoCheckout?: boolean;
    checkoutAfter?: number;
    allowCheckinAfter?: number;
    autoSendRemindMessage?: boolean;
    sendRemindMessageAfter?: number;
    customRemindMessage?: string;
    sendCheckinMessage?: boolean;
    autoGeneratedCheckinMessage?: boolean;
    customCheckinMessage?: string;
    sendCheckoutMessage?: boolean;
    askCustomerLeaveGoogleReview?: boolean;
    googleReviewLink?: string;
    askCustomerLeaveYelpReview?: boolean;
    yelpReviewLink?: string;
    askCustomerLeaveFacebookReview?: boolean;
    facebookReviewLink?: string;
    autoGeneratedCheckoutMessage?: boolean;
    customCheckoutMessage?: string;
    sendClaimedMessage?: boolean;
    autoGeneratedClaimedMessage?: boolean;
    customClaimedMessage?: string;
    sendBirthdayMessage?: boolean;
    showDistanceWaitlistRequest?: boolean;
    sendMessageAddingToWaitlist?: boolean;
    customMessageForNewWaitlist?: string;
    customMessageForWaitlistReady?: string;
}