import { Field, InputType, Int } from "@nestjs/graphql";

@InputType()
export class StoreSettingInput {
    @Field(()=>Boolean)
    autoCheckout?: boolean;
    
    @Field(()=>Int)
    checkoutAfter?: number;
    
    @Field(()=>Int)
    allowCheckinAfter?: number;
    
    @Field(()=>Boolean)
    autoSendRemindMessage?: boolean;
    
    @Field(()=>Int)
    sendRemindMessageAfter?: number;
    
    @Field(()=>String)
    customRemindMessage?: string;
    
    @Field(()=>Boolean)
    sendCheckinMessage?: boolean;
    
    @Field(()=>Boolean)
    autoGeneratedCheckinMessage?: boolean;
    
    @Field(()=>String)
    customCheckinMessage?: string;
    
    @Field(()=>Boolean)
    sendCheckoutMessage?: boolean;
    
    @Field(()=>Boolean)
    askCustomerLeaveGoogleReview?: boolean;
    
    @Field(()=>String)
    googleReviewLink?: string;
    
    @Field(()=>Boolean)
    askCustomerLeaveYelpReview?: boolean;
    
    @Field(()=>String)
    yelpReviewLink?: string;
    
    @Field(()=>Boolean)
    askCustomerLeaveFacebookReview?: boolean;
    
    @Field(()=>String)
    facebookReviewLink?: string;
    
    @Field(()=>Boolean)
    autoGeneratedCheckoutMessage?: boolean;
    
    @Field(()=>String)
    customCheckoutMessage?: string;
    
    @Field(()=>Boolean)
    sendClaimedMessage?: boolean;
    
    @Field(()=>Boolean)
    autoGeneratedClaimedMessage?: boolean;
    
    @Field(()=>String)
    customClaimedMessage?: string;
    
    @Field(()=>Boolean)
    sendBirthdayMessage?: boolean;
    
    @Field(()=>Boolean)
    showDistanceWaitlistRequest?: boolean;
    
    @Field(()=>Boolean)
    sendMessageAddingToWaitlist?: boolean;
    
    @Field(()=>String)
    customMessageForNewWaitlist?: string;
    
    @Field(()=>String)
    customMessageForWaitlistReady?: string;
}